### ISSUE TITLE
Commands does not work

### ISSUE THREAD

**Issue by miloszek2804** [BX-Team/NDailyRewards#26]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Im using essentialsx and valut when i downloaded that plugin. But when i tried to run commands from that plugin problems were showing up 
![image](https://user-images.githubusercontent.com/107253787/201135764-98c127cf-734d-4a60-873a-e02772405375.png)

### To Reproduce

1. Download essentialsx 2.19.7
2. Download Valut
3. Then add Ndailyrewards

### Expected behaviour

that i was allowed to use command /ndailyrewards

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/107253787/201134969-16fe0474-6a3d-48f8-901b-c2de88121d21.png)

![image](https://user-images.githubusercontent.com/107253787/201135014-80b1f337-b3fa-4f02-b2df-538a72ff0c47.png)

### Error log (if applicable)

https://mclo.gs/83lIeFL

### NDailyRewards Version

1.5.4

### Checklist

- [X] I have included a NDailyRewards error log.
- [X] I am using the newest build from https://www.curseforge.com/minecraft/bukkit-plugins/ndailyrewards and the issue still persists.

### Anything else?

That server is on aternos

**Comment by NONPLAYT** [comment]
Thank you for issue, I will fix it soon

**Comment by NONPLAYT** [comment]
so I think I fixed this bug, please wait until new version will be released in bukkit site and update plugin at your server

**Comment by NONPLAYT** [comment]
1.5.5 is now released, you can download it
