### ISSUE TITLE
Missing permission check & Performance issue

### ISSUE THREAD

**Issue by xii69** [BX-Team/NDailyRewards#73]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Hi, when someone joins the server without any permission or "ndailyrewards.user" set to false, the reward menu will automatically open for him, also there is a huge performance impact using MySQL that I have a screenshot I uploaded from a Spark profiler.

### To Reproduce

1- Join without permission / op or join with "ndailyrewards.user" permission set to false
2- The reward menu opens in both scenarios no matter what

### Expected behaviour

There should be a permission to prevent the plugin to open the reward menu

### Screenshots / Videos

![photo_2023_12_16_15_22_56](https://github.com/BX-Team/NDailyRewards/assets/87283583/0e7ebed7-8e23-4bae-8537-41cbaadafd96)

### NDailyRewards Version

2.3.2 & 2.3.3 both tested

### Checklist

- [X] I have included a NDailyRewards error log.
- [X] I am using the newest build from https://modrinth.com/plugin/ndailyrewards and the issue still persists.

**Comment by NONPLAYT** [comment]
I know about the problem with mysql, it has been reported for a long time, but in the end it seemed to be fixed. And about the fact that the GUI opens even if there is no permission, I will look and fix it, just like mysql (at least I will try)

**Comment by xii69** [comment]
Thank you, this is a great plugin, I made a fork and fixed the GUI problem temporarily, but the performance issue is annoying, hope it gets fixed.

**Comment by xii69** [comment]
I guess I found the performance issue cause, in UserManager autosave method which it was cause of a forever loop for saving and executing UPDATE SQL statement, you meant to Remove the DUser after saving it but you was adding it again by mistake, check this out:
https://github.com/xii69/NDailyRewards/commit/703b1df0b586b95c3fa0c224bc874d4251644733

**Comment by NONPLAYT** [comment]
> I guess I found the performance issue cause, in UserManager autosave method which it was cause of a forever loop for saving and executing UPDATE SQL statement, you meant to Remove the DUser after saving it but you was adding it again by mistake, check this out: [xii69@703b1df](https://github.com/xii69/NDailyRewards/commit/703b1df0b586b95c3fa0c224bc874d4251644733)

thanks, I'll check it out soon (I'm sick now)
